// rice/libs/_core/kernel/src/exceptions/error.codes.ts
/**
 * 标准化错误码
 */
export const ErrorCodes = Object.freeze({
  // 通用错误
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // 领域特定错误
  AGGREGATE_INVALID_STATE: 'AGGREGATE_INVALID_STATE',
  ENTITY_ALREADY_EXISTS: 'ENTITY_ALREADY_EXISTS',
  VALUE_OBJECT_INVALID: 'VALUE_OBJECT_INVALID',
  DOMAIN_RULE_VIOLATION: 'DOMAIN_RULE_VIOLATION',
  REPOSITORY_ERROR: 'REPOSITORY_ERROR',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
} as const);

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];